### ISSUE TITLE
When shall the code be released?

### ISSUE THREAD

**Issue by ae86208** [kakaobrain/noc#2]

**Comment by wykang** [comment]
Thank you for your interest in our work :slightly_smiling_face:.
We plan to release the code by next month (2023.1).

**Comment by ae86208** [comment]
Any updates?

**Comment by wykang** [comment]
We apologize for delaying the code release. As other tasks have taken precedence, we are striving to make the code available within the next 1-2 weeks.

**Comment by wykang** [comment]
@ae86208 We sincerely apologize for any inconvenience. The release of the code will be delayed by another two weeks due to our internal reviewing processes.

**Comment by ae86208** [comment]
> @ae86208 We sincerely apologize for any inconvenience. The release of the code will be delayed by another two weeks due to our internal reviewing processes.

Are there any updates? Another 2 weeks have passed.

**Comment by wykang** [comment]
@ae86208 We sincerely apologize for the delay in releasing our code. Finally, we are delighted to inform you that it is now available to the public. 

Additionally, we are thrilled to announce that our work has been accepted at ICCV 2023. For further details, please refer to the updated version of our paper on Arxiv using the following link: https://arxiv.org/abs/2212.13563 .
