### ISSUE TITLE
pre-training time?

### ISSUE THREAD

**Issue by junbum766** [kakaobrain/noc#3]
I wonder about how long it took to pre-train the model with the CC3M dataset.

**Comment by JonghwanMun** [comment]
Thank you for the interest on our work :)

As I remember, the elapsed time is roughly as follows depending on the number of GPUs available,

| GPUs          | Vision Encoder Status | Batch Size | Elapsed Time |
| ------------- | --------------------- | ---------- | ------------ |
| 8 x V100 (1 node)     | Frozen                | 2048       | ~6 hours     |
| 8 x V100 (1 node)     | Unfrozen              | 256        | ~4 days      |
| 64 x V100 (8 node)    | Unfrozen              | 2048       | ~2 days      |

If you use the better network, multi-node training would be faster.

**Comment by junbum766** [comment]
Thanks for answering my question!
So are the weights you posted the unfrozen version of Vision Encoder?

**Comment by JonghwanMun** [comment]
Exactly, we uploaded the unfrozen version (vision encoder trained) with 64 x v100 gpus (2048 batch).

**Comment by junbum766** [comment]
thank you!!!
