### ISSUE TITLE
ImportError: cannot import name 'get_collate_fn' from 'noc.dataset' (<root>/dataset/__init__.py)

### ISSUE THREAD

**Issue by JEILDLWLRMA** [kakaobrain/noc#4]
I'm following the step at README

ImportError: cannot import name 'get_collate_fn' from 'noc.dataset' (<fileroot>/NOC/noc/dataset/__init__.py)

how can I solve it?
I run this command : python3 preprocess/get_noc_bucket.py

**Comment by JonghwanMun** [comment]
Can you try the following command at the root directory (/data/hyeokseung1208/NOC)?
`PYTHONPATH=./ python3 preprocess/get_noc_bucket.py`

**Comment by JEILDLWLRMA** [comment]
Still have same problem...

**Comment by JonghwanMun** [comment]
Or try following:

`PYTHONPATH=./ python3 -m preprocess.get_noc_bucket`

**Comment by JEILDLWLRMA** [comment]
I tried PYTHONPATH=./ python3 -m preprocess.get_noc_bucket
but I got another issue :
Traceback (most recent call last):
  File "/data/hyeokseung1208/anaconda3/envs/NOC/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/data/hyeokseung1208/anaconda3/envs/NOC/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/data/hyeokseung1208/NOC/preprocess/get_noc_bucket.py", line 21, in <module>
    from utils import BasicDataset
ModuleNotFoundError: No module named 'utils'

**Comment by JonghwanMun** [comment]
Can you revise absolute import

https://github.com/kakaobrain/noc/blob/7827a6aa4ce725f51f9e1c1e11389db9fd7cf8ae/preprocess/get_noc_bucket.py#L21
as relative one
`from .utils import BasicDataset`

Actually, with our environment setting, it is working when following README.
So, after setting up the same environment occuring errors, I will debug and then submit a PR for the fix.

Sorry for the inconvinience.

**Comment by JEILDLWLRMA** [comment]
I used conda env and the packages in the conda virtual environment are as follows. Thank you for your efforts:)

# packages in environment at /data/hyeokseung1208/anaconda3/envs/NOC:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
absl-py                   2.1.0                    pypi_0    pypi
aiohttp                   3.8.6                    pypi_0    pypi
aiosignal                 1.3.1                    pypi_0    pypi
antlr4-python3-runtime    4.9.3                    pypi_0    pypi
async-timeout             4.0.3                    pypi_0    pypi
asynctest                 0.13.0                   pypi_0    pypi
attrs                     23.2.0                   pypi_0    pypi
awscli                    1.31.13                  pypi_0    pypi
beautifulsoup4            4.7.1                    pypi_0    pypi
beautifultable            0.7.0                    pypi_0    pypi
blas                      2.16                        mkl    conda-forge
boto3                     1.33.13                  pypi_0    pypi
botocore                  1.33.13                  pypi_0    pypi
braceexpand               0.1.7                    pypi_0    pypi
bzip2                     1.0.8                hd590300_5    conda-forge
ca-certificates           2024.3.11            h06a4308_0  
cachetools                5.3.3                    pypi_0    pypi
certifi                   2024.2.2           pyhd8ed1ab_0    conda-forge
chardet                   4.0.0                    pypi_0    pypi
charset-normalizer        3.3.2                    pypi_0    pypi
click                     8.1.3                    pypi_0    pypi
colorama                  0.4.4                    pypi_0    pypi
cudatoolkit               11.3.1              hb98b00a_13    conda-forge
cycler                    0.11.0                   pypi_0    pypi
decorator                 5.1.1                    pypi_0    pypi
docker                    3.6.0                    pypi_0    pypi
docker-pycreds            0.4.0                    pypi_0    pypi
docutils                  0.16                     pypi_0    pypi
easydict                  1.13                     pypi_0    pypi
evalai                    1.3.16                   pypi_0    pypi
ffmpeg                    4.3                  hf484d3e_0    pytorch
filelock                  3.12.2                   pypi_0    pypi
fonttools                 4.38.0                   pypi_0    pypi
freetype                  2.12.1               h267a509_2    conda-forge
frozenlist                1.3.3                    pypi_0    pypi
fsspec                    2023.1.0                 pypi_0    pypi
ftfy                      6.1.1                    pypi_0    pypi
gmp                       6.3.0                h59595ed_1    conda-forge
gnutls                    3.6.13               h85f3911_1    conda-forge
google-auth               2.29.0                   pypi_0    pypi
google-auth-oauthlib      0.4.6                    pypi_0    pypi
grpcio                    1.62.2                   pypi_0    pypi
huggingface-hub           0.16.4                   pypi_0    pypi
hydra-core                1.3.2                    pypi_0    pypi
idna                      2.10                     pypi_0    pypi
importlib-metadata        6.7.0                    pypi_0    pypi
importlib-resources       5.12.0                   pypi_0    pypi
intel-openmp              2023.1.0         hdb19cb5_46306  
jmespath                  1.0.1                    pypi_0    pypi
joblib                    1.3.2                    pypi_0    pypi
jpeg                      9e                   h0b41bf4_3    conda-forge
kiwisolver                1.4.5                    pypi_0    pypi
lame                      3.100             h166bdaf_1003    conda-forge
lcms2                     2.14                 h6ed2654_0    conda-forge
ld_impl_linux-64          2.38                 h1181459_1  
lerc                      4.0.0                h27087fc_0    conda-forge
libblas                   3.8.0                    16_mkl    conda-forge
libcblas                  3.8.0                    16_mkl    conda-forge
libdeflate                1.14                 h166bdaf_0    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 13.2.0               hc881cc4_6    conda-forge
libgfortran-ng            7.5.0               h14aa051_20    conda-forge
libgfortran4              7.5.0               h14aa051_20    conda-forge
libgomp                   13.2.0               hc881cc4_6    conda-forge
libiconv                  1.17                 hd590300_2    conda-forge
liblapack                 3.8.0                    16_mkl    conda-forge
liblapacke                3.8.0                    16_mkl    conda-forge
libnsl                    2.0.1                hd590300_0    conda-forge
libpng                    1.6.43               h2797004_0    conda-forge
libstdcxx-ng              13.2.0               h95c4c6d_6    conda-forge
libtiff                   4.4.0                h82bc61c_5    conda-forge
libuv                     1.48.0               hd590300_0    conda-forge
libwebp-base              1.4.0                hd590300_0    conda-forge
libxcb                    1.13              h7f98852_1004    conda-forge
libzlib                   1.2.13               hd590300_5    conda-forge
lightning-bolts           0.5.0                    pypi_0    pypi
lightning-utilities       0.10.1                   pypi_0    pypi
lxml                      4.6.2                    pypi_0    pypi
markdown                  3.4.4                    pypi_0    pypi
markupsafe                2.1.5                    pypi_0    pypi
matplotlib                3.5.3                    pypi_0    pypi
mkl                       2020.2                      256  
multidict                 6.0.5                    pypi_0    pypi
mypy-extensions           1.0.0                    pypi_0    pypi
ncurses                   6.4                  h6a678d5_0  
nettle                    3.6                  he412f7d_0    conda-forge
numpy                     1.21.6           py37h976b520_0    conda-forge
oauthlib                  3.2.2                    pypi_0    pypi
omegaconf                 2.3.0                    pypi_0    pypi
openh264                  2.1.1                h780b84a_0    conda-forge
openjpeg                  2.5.0                h7d73246_1    conda-forge
openssl                   3.2.1                hd590300_1    conda-forge
packaging                 24.0                     pypi_0    pypi
pickle5                   0.0.12                   pypi_0    pypi
pillow                    9.2.0            py37h850a105_2    conda-forge
pip                       24.0                     pypi_0    pypi
protobuf                  3.20.3                   pypi_0    pypi
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
pyasn1                    0.5.1                    pypi_0    pypi
pyasn1-modules            0.3.0                    pypi_0    pypi
pycocotools               2.0.7                    pypi_0    pypi
pydeprecate               0.3.2                    pypi_0    pypi
pyparsing                 3.1.2                    pypi_0    pypi
python                    3.7.12          hf930737_100_cpython    conda-forge
python-dateutil           2.7.3                    pypi_0    pypi
python_abi                3.7                     4_cp37m    conda-forge
pytorch                   1.10.0          py3.7_cuda11.3_cudnn8.2.0_0    pytorch
pytorch-lightning         1.7.6                    pypi_0    pypi
pytorch-mutex             1.0                        cuda    pytorch
pyyaml                    6.0.1                    pypi_0    pypi
readline                  8.2                  h5eee18b_0  
regex                     2024.4.16                pypi_0    pypi
requests                  2.25.1                   pypi_0    pypi
requests-oauthlib         2.0.0                    pypi_0    pypi
rsa                       4.7.2                    pypi_0    pypi
s3transfer                0.8.2                    pypi_0    pypi
safetensors               0.4.3                    pypi_0    pypi
scikit-learn              1.0.2                    pypi_0    pypi
scipy                     1.7.3                    pypi_0    pypi
setuptools                59.5.0                   pypi_0    pypi
six                       1.16.0                   pypi_0    pypi
soupsieve                 2.4.1                    pypi_0    pypi
sqlite                    3.41.2               h5eee18b_0  
tensorboard               2.11.2                   pypi_0    pypi
tensorboard-data-server   0.6.1                    pypi_0    pypi
tensorboard-plugin-wit    1.8.1                    pypi_0    pypi
termcolor                 1.1.0                    pypi_0    pypi
threadpoolctl             3.1.0                    pypi_0    pypi
tk                        8.6.12               h1ccaba5_0  
tokenizers                0.13.3                   pypi_0    pypi
torchaudio                0.10.0               py37_cu113    pytorch
torchmetrics              0.11.4                   pypi_0    pypi
torchvision               0.11.0               py37_cu113    pytorch
tqdm                      4.66.2                   pypi_0    pypi
transformers              4.30.2                   pypi_0    pypi
typing_extensions         4.7.1              pyha770c72_0    conda-forge
urllib3                   1.26.18                  pypi_0    pypi
validators                0.12.6                   pypi_0    pypi
wcwidth                   0.2.13                   pypi_0    pypi
websocket-client          1.6.1                    pypi_0    pypi
werkzeug                  2.2.3                    pypi_0    pypi
wheel                     0.38.4           py37h06a4308_0  
xorg-libxau               1.0.11               hd590300_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xz                        5.4.6                h5eee18b_0  
yarl                      1.9.4                    pypi_0    pypi
zipp                      3.15.0                   pypi_0    pypi
zlib                      1.2.13               hd590300_5    conda-forge
zstd                      1.5.5                hfc55251_0    conda-forge

**Comment by JEILDLWLRMA** [comment]
Here is my package list that I installed! thx for your efforts:)
[packages.txt](https://github.com/kakaobrain/noc/files/15127556/packages.txt)

**Comment by JonghwanMun** [comment]
Please remove following line.
https://github.com/kakaobrain/noc/blob/7827a6aa4ce725f51f9e1c1e11389db9fd7cf8ae/noc/models/lightning/captioner.py#L28

And then, insert it into line 183 as follows:
```
try:
    from noc.utils import main_utils  # add this
    main_utils.save_config_to_disk(self.cfg)
except FileNotFoundError as err:
    logging.info(err)
```

Can you try above modification (which avoids the circular import issue)?

**Comment by JEILDLWLRMA** [comment]
I tried the above and the issue was resolved! Thank you and have a nice day:)
